from typing import Any, Dict, List, Optional, cast

from services.supabase_client import supabase, safe_insert, safe_update


# Actual columns from Supabase content_queue table
CONTENT_COLUMNS = {
    "id",
    "generated_post",
    "hook",
    "cta",
    "status",
    "platform",
    "payload",
    "created_at",
    "updated_at",
    "infographic_url"
}


def _filter_content_payload(
    data: Dict[str, Any]
) -> Dict[str, Any]:

    payload = {
        k: v
        for k, v in data.items()
        if k in CONTENT_COLUMNS and v is not None
    }

    return payload


def enqueue_generated_content(content_data: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Enqueue content generated by the content agent into the content queue."""
    print("[content_queue_service] enqueue_generated_content called with:", content_data)
    try:
        generated_post = content_data["linkedin_post"]
    except KeyError as e:
        print("[content_queue_service] missing 'linkedin_post' in content_data")
        raise KeyError("content_data missing required key: 'linkedin_post'") from e

    try:
        response = safe_insert("content_queue", {
            "generated_post": generated_post,
            "hook": content_data.get("hook"),
            "cta": content_data.get("cta"),
            "status": "draft",
            "payload": content_data
        })

        print("[content_queue_service] supabase.insert response.error:", getattr(response, 'error', None))
        print("[content_queue_service] supabase.insert returned rows:", response.data)

        return cast(List[Dict[str, Any]], response.data or [])
    except Exception as e:
        print(f"Error enqueuing content: {e}")
        raise


def get_content(
    status: Optional[str] = None,
    platform: Optional[str] = None,
    limit: int = 100
) -> List[Dict[str, Any]]:
    """Get content items from the content queue with optional filtering."""
    try:
        print(f"[content_queue_service] get_content called status={status} platform={platform} limit={limit}")
        query = supabase.table("content_queue").select("*")

        if status:
            query = query.eq("status", status)

        if platform:
            query = query.eq("platform", platform)

        response = query.order("created_at", desc=True).limit(limit).execute()

        print("[content_queue_service] supabase.select response.error:", getattr(response, 'error', None))
        print("[content_queue_service] supabase.select returned rows count:", len(response.data or []))

        return cast(List[Dict[str, Any]], response.data or [])
    except Exception as e:
        print(f"Error fetching content: {e}")
        raise


def get_content_by_id(content_id: int) -> Optional[Dict[str, Any]]:
    """Get a single content item by id."""
    try:
        print(f"[content_queue_service] get_content_by_id called id={content_id}")
        response = (
            supabase
            .table("content_queue")
            .select("*")
            .eq("id", content_id)
            .limit(1)
            .execute()
        )

        print("[content_queue_service] supabase.select response.error:", getattr(response, 'error', None))
        rows = response.data or []
        print("[content_queue_service] supabase.select returned rows count:", len(rows))

        if len(rows) == 0:
            return None

        row = rows[0]
        # Ensure we return a mapping/dict for type checkers and consumers
        if not isinstance(row, dict):
            print("[content_queue_service] Warning: row is not a dict, returning None", row)
            return None

        return cast(Dict[str, Any], row)
    except Exception as e:
        print(f"Error fetching content by id: {e}")
        raise


def create_content(data: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Create a new content item in the content queue."""
    try:
        payload = _filter_content_payload(data)

        if not payload:
            raise ValueError("No valid fields to insert")

        print("\nPAYLOAD TO SUPABASE:")
        print(payload)

        response = safe_insert("content_queue", payload)

        print("[content_queue_service] supabase.insert response.error:", getattr(response, 'error', None))
        print("[content_queue_service] supabase.insert returned rows:", response.data)

        return cast(List[Dict[str, Any]], response.data or [])
    except Exception as e:
        print(f"Error creating content: {e}")
        raise


def update_content(content_id: int, updates: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """Update an existing content item in the content queue."""
    try:
        payload = _filter_content_payload(updates)

        if not payload:
            return None

        print(f"\nUPDATING CONTENT {content_id}:")
        print(payload)

        response = (
            supabase
            .table("content_queue")
            .update(payload)
            .eq("id", content_id)
            .execute()
        )

        print("[content_queue_service] supabase.update response.error:", getattr(response, 'error', None))
        print("[content_queue_service] supabase.update returned rows:", response.data)

        return cast(List[Dict[str, Any]], response.data or [])
    except Exception as e:
        print(f"Error updating content: {e}")
        raise