from typing import Any, Dict, List, Optional, cast

from services.supabase_client import supabase


# Actual columns from Supabase content_queue table
CONTENT_COLUMNS = {
    "id",
    "generated_post",
    "hook",
    "cta",
    "status",
    "platform",
    "payload",
    "created_at",
    "updated_at"
}


def _filter_content_payload(
    data: Dict[str, Any]
) -> Dict[str, Any]:

    payload = {
        k: v
        for k, v in data.items()
        if k in CONTENT_COLUMNS and v is not None
    }

    return payload


def enqueue_generated_content(content_data: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Enqueue content generated by the content agent into the content queue."""
    try:
        generated_post = content_data["linkedin_post"]
    except KeyError as e:
        raise KeyError("content_data missing required key: 'linkedin_post'") from e

    try:
        response = (
            supabase
            .table("content_queue")
            .insert({
                "generated_post": generated_post,
                "hook": content_data.get("hook"),
                "cta": content_data.get("cta"),
                "status": "draft",
                "payload": content_data
            })
            .execute()
        )

        return cast(List[Dict[str, Any]], response.data or [])
    except Exception as e:
        print(f"Error enqueuing content: {e}")
        raise


def get_content(
    status: Optional[str] = None,
    platform: Optional[str] = None,
    limit: int = 100
) -> List[Dict[str, Any]]:
    """Get content items from the content queue with optional filtering."""
    try:
        query = supabase.table("content_queue").select("*")

        if status:
            query = query.eq("status", status)

        if platform:
            query = query.eq("platform", platform)

        response = query.order("created_at", desc=True).limit(limit).execute()

        return cast(List[Dict[str, Any]], response.data or [])
    except Exception as e:
        print(f"Error fetching content: {e}")
        raise


def create_content(data: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Create a new content item in the content queue."""
    try:
        payload = _filter_content_payload(data)

        if not payload:
            raise ValueError("No valid fields to insert")

        print("\nPAYLOAD TO SUPABASE:")
        print(payload)

        response = (
            supabase
            .table("content_queue")
            .insert(payload)
            .execute()
        )

        return cast(List[Dict[str, Any]], response.data or [])
    except Exception as e:
        print(f"Error creating content: {e}")
        raise


def update_content(content_id: int, updates: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """Update an existing content item in the content queue."""
    try:
        payload = _filter_content_payload(updates)

        if not payload:
            return None

        print(f"\nUPDATING CONTENT {content_id}:")
        print(payload)

        response = (
            supabase
            .table("content_queue")
            .update(payload)
            .eq("id", content_id)
            .execute()
        )

        return cast(List[Dict[str, Any]], response.data or [])
    except Exception as e:
        print(f"Error updating content: {e}")
        raise